//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ideas4AppsHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string telephone_number { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public string status { get; set; }
        public string business_hours { get; set; }
        public string tags { get; set; }
        public string weburl { get; set; }
        public byte[] photo { get; set; }
        public string category { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
